//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutenticaPracticalTask.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutenticaPracticalTask.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name cannot be empty..
        /// </summary>
        internal static string CityNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("CityNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City not found..
        /// </summary>
        internal static string CityNotFound {
            get {
                return ResourceManager.GetString("CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all pinpoints.
        /// </summary>
        internal static string ClearMarkers {
            get {
                return ResourceManager.GetString("ClearMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AW_VIETU_CENTROIDI.csv.
        /// </summary>
        internal static string CSVFileName {
            get {
                return ResourceManager.GetString("CSVFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furthest east point in Latvia..
        /// </summary>
        internal static string EastPoint {
            get {
                return ResourceManager.GetString("EastPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furthest north point in Latvia..
        /// </summary>
        internal static string NorthPoint {
            get {
                return ResourceManager.GetString("NorthPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furthest south point in Latvia..
        /// </summary>
        internal static string SouthPoint {
            get {
                return ResourceManager.GetString("SouthPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furthest west point in Latvia..
        /// </summary>
        internal static string WestPoint {
            get {
                return ResourceManager.GetString("WestPoint", resourceCulture);
            }
        }
    }
}
